### ISSUE TITLE
Chakra 源码在哪儿？

### ISSUE THREAD

**Issue by xcatliu** [lazyparser/chakra-internals#1]
Chakra 源码在哪儿？

**Comment by lazyparser** [comment]
Hi @xcatliu 

我还没有看到源代码, 上个月的时候微软的开发人员说会放在github上:
https://github.com/Microsoft

这个repo里面不会放源代码, 收集的chakra相关的学习资源 :-)

**Comment by xcatliu** [comment]
赞，Chakra 开源后可以贴个源代码的链接

**Comment by lazyparser** [comment]
嗯, OK :)

**Comment by xcatliu** [comment]
https://github.com/Microsoft/ChakraCore
这个是吗？

**Comment by lazyparser** [comment]
没错 :-)
